### ISSUE TITLE
Expected 3 streams, got 1

### ISSUE THREAD

**Issue by sergava** [atilaromero/telegram-desktop-decrypt#10]
![0987](https://user-images.githubusercontent.com/38960886/96350192-dba34480-10b4-11eb-9e77-03ad4763caa4.png)
Here is a screenshot. What should I do?

**Comment by jkmartindale** [comment]
This code is over a year old and doesn't support the tdata format used by recent versions of Telegram Desktop

**Comment by sergava** [comment]
Thanks
